# Dockerfile.django
FROM python:3.12-slim

# Imposta la directory di lavoro
WORKDIR /app

# Copia i requirements e installa le dipendenze
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copia il progetto
COPY . .

# Espone la porta Django
EXPOSE 8000

# Avvia il server Django

CMD ["python", "manage.py", "runserver", "--noreload", "0.0.0.0:8000"]