# Generated by Django 4.2.29 on 2026-04-13 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certchain', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='student_index',
            field=models.PositiveIntegerField(blank=True, help_text='Indice per i file JSON (es. 1 per s1)', null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Amministratore'), ('CERTIFYING_AUTHORITY', 'Ente Certificatore'), ('STUDENT', 'Studente'), ('COMPANY', 'Azienda')], editable=False, max_length=30),
        ),
    ]
