# Generated by Django 4.2.29 on 2026-04-30 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certchain', '0002_customuser_student_index_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='wallet_address',
            field=models.CharField(blank=True, help_text='Indirizzo del wallet Ethereum/MetaMask', max_length=42, null=True, unique=True),
        ),
    ]
